### ISSUE TITLE
关于底部时间和彩带

### ISSUE THREAD

**Issue by Kevan1017** [shiyiya/Plain#1]
- 底部的时间有些别扭，每次刷新网页都会重新渲染dom，影响性能
- 彩带可以增加开关设置，毕竟有些人不喜欢有彩带，影响阅读

**Comment by shiyiya** [comment]
- 底部 pjax 不刷新，除非你手动刷新整个网页。
- 如果不需要彩带，删除此处。（暂时）
![image](https://user-images.githubusercontent.com/34017352/40757000-e44a4f70-64b8-11e8-916a-71008f6861ce.png)
```,document.onclick=i,(document.ontouchstart=i)()```
**感谢你的意见，但是不用重复开多个issue，直接再此回复**

**Comment by shiyiya** [comment]
- 底部 pjax 不刷新，除非你手动刷新整个网页。
- 已增加该选项。
**感谢你的意见**
