### ISSUE TITLE
pjax跳转到文章页面无内容

### ISSUE THREAD

**Issue by Taskeren** [shiyiya/Plain#4]
**Describe the bug**  
pjax跳转到文章页面文章无内容，其他正常  

**To Reproduce**  
[我的博客](https://blog.targ.top)  

**Screenshots**  
![hrk8xhd2l5t4yqnn wyvi8m](https://user-images.githubusercontent.com/17310943/42418791-2471443e-82da-11e8-8412-965b865d9ca6.png)

我在我的博客里把评论区改成了Gitment，不知道是不是因为这个。
还有，我的博客是部署在Coding Pages里的，不知道会不会有影响。
望解答，谢谢！

**Comment by shiyiya** [comment]
有可能是 `Gitment` 导致的问题，你可以尝试移除。

**Comment by shiyiya** [comment]
额，你 `Marked` 使用姿势不对，over。
