### ISSUE TITLE
1.2版本，评论位置没有输入网址的框

### ISSUE THREAD

**Issue by linhaii** [shiyiya/Plain#6]
目前最新typecho正式版，主题版本1.2，在releases界面下载，未更改任何代码。后来设置也未更改。

但是和1.1相比，评论框位置，输入网址的地方没了。

![截图](https://user-images.githubusercontent.com/32946306/44587237-eddf0c00-a7e4-11e8-8f8f-7834f5dbc95d.png)

在不同的主机、不同人的博客在线测试，均是如此。本地wamp测试也是如此，希望作者能够修复，谢谢。

**Comment by shiyiya** [comment]
设置=>评论=>必须填写网址

**Comment by shiyiya** [comment]
如果没问题我就关闭这个 issuse 了

**Comment by linhaii** [comment]
那样的话如果有些人没有网址怎么办呢？

**Comment by shiyiya** [comment]
现在是必填则显示非必填则不显示，明天我改回去吧。
