### ISSUE TITLE
不维护了吗？

### ISSUE THREAD

**Issue by ethan0924** [shiyiya/Plain#7]
现在不能正常使用了

**Comment by shiyiya** [comment]
能描述遇到什么问题了么

**Comment by ethan0924** [comment]
![image-20220819000233776](http://cdn.tqqj.top//202208190002888.png)

**Comment by ethan0924** [comment]
打开外观出现以下错误：
Argument 1 passed to _e0 must be of the type string, null given, called in /www/wwwroot/xxx.com /usr/themes/Plain/header.php on line 66
